version: '3.9'
services:
  postgres:
    image: postgres:latest
    env_file: ../configs/postgres/postgres.env
    expose:
      - '5432'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  frontend:
    build:
      context: ../configs
      target: prod-frontend
    volumes:
      - ../..:/new_project_server
      - frontend-dist:/new_project_server/frontend/dist

  backend:
    build:
      context: ../configs
      target: prod-backend
    expose:
      - '8000'
    ports:
      - '8000:8000'
    links:
      - postgres
    volumes:
      - ../..:/new_project_server
      - backend-key:/key

  ngnix:
    image: nginx:latest
    expose:
      - '80'
    ports:
      - '80:80'
    links:
      - frontend
      - backend
    volumes:
      - ../configs/nginx/prod/nginx.conf:/etc/nginx/nginx.conf
      - frontend-dist:/static

volumes:
  frontend-dist:
  backend-key:
  postgres-data:
